version: "3.7"

services:
  app:
    image: acim/go-reflex
    environment:
      - RACE_DETECTOR=1
      - GOFLAGS="-buildvcs=false"
      - MYSQL_DSN=root:@tcp(mysql:3306)/sendo_db?charset=utf8mb4&parseTime=True&loc=Local
    volumes:
      - .:/app
    ports:
      - 4040:8080
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - intranet
  # app:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   environment:
  #     MYSQL_DSN: "root:@tcp(mysql:3306)/sendo_db?charset=utf8mb4&parseTime=True&loc=Local"
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - intranet
  mysql:
    image: mysql:8.0.32
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "sendo_db"
    ports:
      - 3301:3306
    networks:
      - intranet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    networks:
      - intranet
  minio:
    image: minio/minio
    volumes:
      - ./data/minio/data:/data
      - ./data/minio/config:/root/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=sendo_minio
      - MINIO_ROOT_PASSWORD=sendo_minio97
    command: server --console-address ":9001" /data
    networks:
      - intranet
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq/data/:/var/lib/rabbitmq
      - ./data/rabbitmq/log/:/var/log/rabbitmq
    restart: always
    networks:
      - intranet
networks:
  intranet:
